
-- MySQL Script generated by MySQL Workbench

-- 11/16/17 10:10:51

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------

-- Schema Twitch

-- -----------------------------------------------------


-- -----------------------------------------------------

-- Schema Twitch

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Twitch` DEFAULT CHARACTER SET utf8 ;

USE `Twitch` ;


-- -----------------------------------------------------

-- Table `Twitch`.`Streamer`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Streamer` (

  `streamerID` INT NOT NULL AUTO_INCREMENT,

  `ChannelName` VARCHAR(13) NOT NULL,

  `totalViews` INT DEFAULT 0,

  `totalFollowers` INT DEFAULT 0,

  `subscriptionButton` ENUM('Yes','No') DEFAULT 'No',

  `totalSubscriptions` INT DEFAULT 0,

  `pcSpecs` LONGTEXT NULL,

  `Mature` ENUM('Yes','No') DEFAULT 'No',

  `Donations` DECIMAL NULL,

  `subIcon` ENUM('Yes','No') DEFAULT 'No',

  `Moderators` MEDIUMTEXT NULL,

  PRIMARY KEY (`streamerID`),

  UNIQUE INDEX `ChannelName_UNIQUE` (`ChannelName` ASC),

  UNIQUE INDEX `streamerID_UNIQUE` (`streamerID` ASC))

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Viewer`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Viewer` (

  `viewerID` INT NOT NULL AUTO_INCREMENT,

  `UserName` VARCHAR(45) NOT NULL,

  `JoinDate` DATETIME DEFAULT NOW(),

  `Doners` ENUM('Yes','No') DEFAULT 'No',

  `Moderator` ENUM('Yes','No') DEFAULT 'No',

  PRIMARY KEY (`viewerID`))





ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Game`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Game` (

  `gameID` INT NOT NULL AUTO_INCREMENT,

  `Genre` MEDIUMTEXT NOT NULL,

  `gameName` MEDIUMTEXT NOT NULL,

  PRIMARY KEY (`gameID`))

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Moderator`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Moderator` (

  `streamerID` INT NOT NULL,

  `viewerID` INT NOT NULL,

  INDEX `streamerID_idx` (`streamerID` ASC),

  INDEX `viewerID_idx` (`viewerID` ASC),

  CONSTRAINT `streamerID`

    FOREIGN KEY (`streamerID`)

    REFERENCES `Twitch`.`Streamer` (`streamerID`)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION,

  CONSTRAINT `viewerID`

    FOREIGN KEY (`viewerID`)

    REFERENCES `Twitch`.`Viewer` (`viewerID`)

    ON DELETE NO ACTION

    ON UPDATE NO ACTION)

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`GameStreaming`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`GameStreaming` (

  `streamerID` INT NOT NULL,

  `gameID` INT NOT NULL,

  INDEX `streamerID_idx` (`streamerID` ASC),

  INDEX `gameID_idx` (`gameID` ASC))



ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



