
-- MySQL Script generated by MySQL Workbench

-- 11/16/17 10:10:51

-- Model: New Model    Version: 1.0

-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------

-- Schema Twitch

-- -----------------------------------------------------


-- -----------------------------------------------------

-- Schema Twitch

-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `Twitch` DEFAULT CHARACTER SET utf8 ;

USE `Twitch` ;


-- -----------------------------------------------------

-- Table `Twitch`.`Streamer`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Streamer` (

  `streamerID` INT NOT NULL AUTO_INCREMENT,

  `ChannelName` VARCHAR(45) NOT NULL,

  `totalViews` INT DEFAULT 0,

  `totalFollowers` INT DEFAULT 0,

  `subscriptionButton` ENUM('Yes','No') DEFAULT 'No',

  `totalSubscriptions` INT DEFAULT 0,

  `Processor` INT NULL,

  `Mature` ENUM('Yes','No') DEFAULT 'No',

  `Donations` DECIMAL NULL,

  `subIcon` ENUM('Yes','No') DEFAULT 'No',

  `Moderators` MEDIUMTEXT NULL,

  PRIMARY KEY (`streamerID`),

  UNIQUE INDEX `ChannelName_UNIQUE` (`ChannelName` ASC),

  UNIQUE INDEX `streamerID_UNIQUE` (`streamerID` ASC))

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Viewer`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Viewer` (

  `viewerID` INT NOT NULL AUTO_INCREMENT,

  `UserName` VARCHAR(45) NOT NULL,

  `JoinDate` DATETIME DEFAULT NOW(),

  `Doners` ENUM('Yes','No') DEFAULT 'No',

  `Moderator` ENUM('Yes','No') DEFAULT 'No',

  PRIMARY KEY (`viewerID`))





ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Game`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Game` (

  `gameID` INT NOT NULL AUTO_INCREMENT,

  `Genre` MEDIUMTEXT NOT NULL,

  `gameName` MEDIUMTEXT NOT NULL,

  PRIMARY KEY (`gameID`))

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`Moderator`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`Moderator` (

  `streamerID` INT NOT NULL,

  `viewerID` INT NOT NULL,

  INDEX `streamerID_idx` (`streamerID` ASC),

  INDEX `viewerID_idx` (`viewerID` ASC))

ENGINE = InnoDB;



-- -----------------------------------------------------

-- Table `Twitch`.`GameStreaming`

-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Twitch`.`GameStreaming` (

  `streamerID` INT NOT NULL,

  `gameID` INT NOT NULL,

  INDEX `streamerID_idx` (`streamerID` ASC),

  INDEX `gameID_idx` (`gameID` ASC))



ENGINE = InnoDB;

-- ----------------------------------------------------
-- Update and Add info throughout
-- ----------------------------------------------------

ALTER TABLE streamer ADD viewerID INT(45) AFTER streamerID;
Set sql_safe_updates = 0;
Insert into streamer (ChannelName)
Values
("Blah"),
("Bleh"),
("Grg"),
("Ilon"),
("Nief"),
("Peli"),
("Nyme"),
("Queo"),
("Buej"),
("Mnop"),
("Zpol"),
("Ypoe"),
("Rety"),
("Buppy"),
("Rily"),
("Loppy"),
("Wuet"),
("Leoh"),
("Vino"),
("Seco");

UPDATE streamer
SET totalViews = FLOOR(RAND(10)*2000),
    totalFollowers =  FLOOR(RAND(10)*totalViews),
    subscriptionButton = FLOOR(RAND() * 2) + 1,
    Mature = FLOOR(RAND() * 2) + 1,
    subIcon = FLOOR(RAND() * 2) + 1,
    Donations = FLOOR(RAND(10)*1500),
    Processor = FLOOR(RAND() * 4) + 4,
    totalSubscriptions = CASE
		WHEN subscriptionButton = "Yes" THEN FLOOR(RAND(10)*totalFollowers)
        ELSE totalSubscriptions
        END;

Insert into viewer (UserName)
Values
("Hello"),
("Bob"),
("Heaven"),
("Seth"),
("John"),
("Charles"),
("Jordan"),
("Stacy"),
("Amanda"),
("Thor"),
("Wonderwoman"),
("Steve"),
("Gregg"),
("Amaz"),
("Kripparian"),
("Riggins"),
("TimtheTatman"),
("iijeriichoii"),
("OneForAll_Gaming"),
("Seraph"),
("Donald_Trump");

UPDATE viewer
SET Doners = FLOOR(RAND() * 2) + 1,
    Moderator =  FLOOR(RAND() * 2) + 1,
    JoinDate = DATE_ADD('2011-06-05', INTERVAL  2356*rand() DAY);
UPDATE streamer SET viewerID = streamerID;

INSERT INTO game (Genre, gameName) 
VALUES 
("FPS","Rainbow Six Siege"),
("Sandbox","Minecraft"),
("Simulation","Star Citizen"),
("FPS","Call of Duty"),
("MMORPG","World of Warcraft"),
("Sports","Madden NFL"),
("Sandbox","Ark Survival Evolved"),
("Racing","Forza"),
("Racing","Mario Kart"),
("Action Adventure","Lego Batman"),
("Action Adventure","Skylanders"),
("Action Adventure","Lego Star Wars"),
("RPG","Kingdom Hearts"),
("RPG","Skyrim"),
("FPS","Player Unknown Battlegrounds"),
("FPS","Destiny 2"),
("Simulation","Farm Simulator"),
("MMORPG","Aion Online"),
("Sports","Fifa"),
("Action Adventure","Disney Infinity"),
("RPG","Dragon Age");

UPDATE streamer 
INNER JOIN viewer ON viewer.viewerID
SET 
    channelName = viewer.UserName
    
WHERE
    viewer.viewerID = streamer.streamerID;


SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



